export interface RpmComponent {
  id: number;
  name: string;
  version: string;
  category: string;
  status: 'REGISTERED' | 'STANDBY' | 'ERROR';
  fileExt: 'RPMRegistration';
}

export const RPM_COMPONENTS: RpmComponent[] = [
  { id: 1, name: "Apache Tomcat", version: "9.0.30", category: "Web Application Server", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 2, name: "JDK", version: "8u275-b01 (OpenJDK Runtime)", category: "Java Runtime Environment", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 3, name: "Apache HTTP Server", version: "2.4.39", category: "Web Server", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 4, name: "Apache Cassandra", version: "3.11.8", category: "NoSQL Database", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 5, name: "MySQL Connector/J", version: "8.0.19", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 6, name: "Python", version: "3.8.5", category: "Programming Language", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 7, name: "JDBC Driver for MySQL", version: "5.1.53-1+deb10u1", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 8, name: "PostgreSQL Client Library", version: "13.2 (14.3)", category: "Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 9, name: "MSSQL Driver for JDBC", version: "14.0", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 10, name: "Apache Derby", version: "10.10.4.3 (Oracle JET)", category: "Relational Database", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 11, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 12, name: "Apache Spark", version: "3.1.2", category: "Data Processing Engine", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 13, name: "Apache Flink", version: "1.11.5", category: "Data Processing Engine", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 14, name: "Apache Airflow", version: "1.10.1", category: "Workflow Orchestrator", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 15, name: "Kotlin Coroutines for Java", version: "1.6.0 (incubating)", category: "Asynchronous Library", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 16, name: "RPM Registration", version: "9.0.30-b01", category: "System Utility", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 17, name: "JDBC Driver for Oracle Database", version: "18.1.0.0-248", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 18, name: "Kafka Connect", version: "2.5.1", category: "Streaming Connector", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 19, name: "Apache Cassandra Connector for Apache Kafka", version: "3.11.8", category: "Connector", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 20, name: "Kotlin Coroutines for Java", version: "1.6.0 (incubating)", category: "Asynchronous Library", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 21, name: "JDBC Driver for PostgreSQL", version: "42.2.8", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 22, name: "Hadoop MapReduce", version: "3.3.2 (Java API)", category: "Distributed Processing", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 23, name: "Apache Avro", version: "1.7.4", category: "Serialization Framework", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 24, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 25, name: "Kafka Connector for Elasticsearch", version: "2.4.0-rc1", category: "Connector", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 26, name: "RPM Registration", version: "9.0.30-b01", category: "System Utility", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 27, name: "Apache Cassandra Connector for Apache Hadoop Yarn", version: "3.11.8", category: "Connector", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 28, name: "JDBC Driver for MariaDB", version: "10.5.13 (Oracle JET)", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 29, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 30, name: "Kotlin Coroutines for Java", version: "1.6.0 (incubating)", category: "Asynchronous Library", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 31, name: "Apache Spark", version: "3.1.2", category: "Data Processing Engine", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 32, name: "Apache Flink", version: "1.11.5", category: "Data Processing Engine", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 33, name: "Apache Airflow", version: "1.10.1", category: "Workflow Orchestrator", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 34, name: "JDBC Driver for IBM MQ", version: "8.5.0 (Oracle JET)", category: "Database Driver", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 35, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 36, name: "Kotlin Coroutines for Java", version: "1.6.0 (incubating)", category: "Asynchronous Library", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 37, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 38, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 39, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 40, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 41, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 42, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 43, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 44, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 45, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 46, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 47, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 48, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 49, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 50, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 51, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 52, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 53, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 54, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 55, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 56, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 57, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 58, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 59, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 60, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 61, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 62, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 63, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 64, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 65, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 66, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 67, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 68, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 69, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 70, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 71, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 72, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 73, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 74, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 75, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 76, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 77, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 78, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 79, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 80, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 81, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 82, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 83, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 84, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 85, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 86, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 87, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 88, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 89, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 90, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 91, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 92, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 93, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 94, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 95, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 96, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 97, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 98, name: "Apache Druid", version: "1.15.2", category: "Real-time Analytics", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 99, name: "Kafka Streams", version: "3.1.1", category: "Streaming Platform", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 100, name: "Cassandra Data Transfer Objects (DTOs)", version: "4.7.0", category: "Data Structure", status: "REGISTERED", fileExt: "RPMRegistration" },
  { id: 101, name: "HBase Client Library for Java", version: "0.12.0 (incubating)", category: "NoSQL Database Client", status: "REGISTERED", fileExt: "RPMRegistration" }
];
